name: Update README cards

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v6

      - name: Generate stats card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: stats
          # On utilise TON secret ici
          token: ${{ secrets.MY_PERSONAL_TOKEN }}
          options: username=${{ github.repository_owner }}&show_icons=true&theme=tokyonight&count_private=true&include_all_commits=true&hide_border=true&hide=stars,issues,prs

      - name: Generate top languages card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: top-langs
          token: ${{ secrets.MY_PERSONAL_TOKEN }}
          options: username=${{ github.repository_owner }}&layout=compact&theme=tokyonight&count_private=true&hide=jupyter%20notebook,html,css&hide_border=true

      - name: Generate streak card
        run: |
          mkdir -p profile
          curl "https://github-readme-streak-stats.herokuapp.com/?user=${{ github.repository_owner }}&theme=tokyonight&hide_border=true" -o profile/streak.svg

      - name: Commit and Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add profile/*.svg
          git commit -m "Update README cards" || true
          git pull --rebase origin main
          git push
